### ISSUE TITLE
TestUpdateConnectionOnNSEUpdate fails on CI

### ISSUE THREAD

**Issue by lobkovilya** [networkservicemesh/networkservicemesh#1612]
## Failure Information (for bugs)
https://circleci.com/gh/networkservicemesh/networkservicemesh/99566?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by lobkovilya** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/99687?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by edwarnicke** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/101589?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by denis-tingajkin** [comment]
by simple investigation found that the problem related to nsm monitoring staff. I guess it is fixed by https://github.com/networkservicemesh/networkservicemesh/pull/1631

**Comment by denis-tingajkin** [comment]
Not fixed.
Still reproducialbe: https://circleci.com/gh/networkservicemesh/networkservicemesh/102312?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by lobkovilya** [comment]
Still reproducible: 
https://circleci.com/gh/networkservicemesh/networkservicemesh/106911?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by denis-tingajkin** [comment]
@lobkovilya as I can see, the issue reproducing only on aws and almost on each build... Can it be related to some problems on aws?

**Comment by denis-tingajkin** [comment]
@lobkovilya by simple investigation found that we have `TRACER_ENABLED=true` for monitoring pod in test. Do we have private env `TRACER_ENABLED=true` on circleci?

**Comment by lobkovilya** [comment]
idk, but disabling tracing allows us to hide the root problem. Seems like the main fail reason is incorrectly written test
