### ISSUE TITLE
NSMD container of NSMGR stops after working for some time and increases memory usage of overall cluster

### ISSUE THREAD

**Issue by abhiranjeet** [networkservicemesh/networkservicemesh#2228]
I had NSM components running fine, but a while ago, the **nsmd** container inside **nsmgr** (on all worker nodes) has stopped working. Restarted entire NSM after sometime and it worked, but I supposed it should be running as long as my cluster's status is healthy. I've checked the logs using command "kubectl logs -f nsmgr-pod-name nsmd". 

Also there is an issue with memory usage spiking up for nsmd container. Enclosing logs and snapshots of pod / container status.
Thanks in advance !

Logs : https://slack-files.com/T08PSQ7BQ-F01K2BFAW7J-11c0b73178
![image](https://user-images.githubusercontent.com/65591112/104151322-bcd9f300-5402-11eb-82ed-101a6bb4ed97.png)
![image](https://user-images.githubusercontent.com/65591112/104151306-ae8bd700-5402-11eb-9b33-4a433619f8f5.png)

**Comment by haiodo** [comment]
@Tiberivs is started to look into this issue.

**Comment by Tiberivs** [comment]
@abhiranjeet, could you provide more information for the issue? Log of previous instance (`kubectl logs -p nsmgr-pod-name nsmd`) of the `nsmd` container and pod details (`kubectl describe pod nsmgr-pod-name`) will be very helpful.

**Comment by abhiranjeet** [comment]
Sure. But these new logs belong to new cluster I created after the above mentioned problem was repeating.
[nsmd-describe.txt](https://github.com/networkservicemesh/networkservicemesh/files/5848086/nsmd-describe.txt)
[nsmd-logs.txt](https://github.com/networkservicemesh/networkservicemesh/files/5848096/nsmd-logs.txt)

**Comment by edwarnicke** [comment]
@abhiranjeet We think we have now fixed your problem on master, could you check and let us know if you think its fixed?

**Comment by abhiranjeet** [comment]
@edwarnicke Sorry for responding late. But the problem still persists. "nsmd" container stopped after working for 21 hrs. I am trying to get the logs, but they return an error.

Error from server (BadRequest): previous terminated container "nsmd" in pod "nsmgr-4rq6g" not found
Error from server (BadRequest): previous terminated container "nsmdp" in pod "nsmgr-4rq6g" not found
Error from server (BadRequest): previous terminated container "nsmd-k8s" in pod "nsmgr-4rq6g" not found

Here is a snap of memory utilization of nsmgr, which increase significantly to 2 GB.

![image](https://user-images.githubusercontent.com/65591112/110097404-fe649a00-7dc4-11eb-94ee-267f582f970e.png)

**Comment by Tiberivs** [comment]
@abhiranjeet are you using the master branch? Could you give me your commit id?

**Comment by abhiranjeet** [comment]
I am not using a master branch per se. I am simply deploying nsm on a kubernetes cluster using kubeadm. To deploy nsm, I am using helm commands from this link : https://networkservicemesh.io/docs/setup/run/
